In [1]:
!pwd

/Users/jasonssdev/Dev/Learning/UC/mcd-data-analysis

In [2]:
from utils.paths import PROJECT_ROOT, DATA_RAW_DIR

In [3]:
data_path = str(DATA_RAW_DIR / "datos.xls")
print(f"Data path: {data_path}")

Data path: /Users/jasonssdev/Dev/Learning/UC/mcd-data-analysis/data/raw/datos.xls

In [4]:
import pandas as pd

In [5]:
df_grd = pd.read_excel(io=data_path, sheet_name="GRD", header=0, index_col=None)
df_grd.head()

  ID GRD    Nombre GRD  Costo resolución en Clínica Privada [MM$]
0   GRD1     Coronario                                      7.917
1   GRD2      Hepático                                      3.417
2   GRD3  Respiratorio                                      2.915
3   GRD4         Renal                                      6.188
4   GRD5   Neurológico                                      6.782

In [6]:
df_hospitales = pd.read_excel(io=data_path, sheet_name="Hospitales", header=0, index_col=None)
df_hospitales.head()

,Nombre Servicio de Salud,Nombre Establecimiento,Área Cuidados Intensivos Adultos,Área Cuidados Intermedios Adulto,Total Camas Críticas,Máxima cantidad de camas a aumetar,Costo de instalar una cama [MM$],Costo de operación anual de una cama [MM$],Costo diario GRD1 [MM$],Costo diario GRD2 [MM$],Costo diario GRD3 [MM$],Costo diario GRD4 [MM$],Costo diario GRD5 [MM$],Costo diario GRD6 [MM$],Costo diario GRD7 [MM$],Costo diario GRD8 [MM$],Costo diario GRD9 [MM$],Costo diario GRD10 [MM$]
0,Metropolitano Norte ...,Complejo Hospitalario San José,11,33,44,10,1407,47.2,0.593,0.509,0.367,0.492,0.524,0.405,0.571,0.474,0.498,0.305
1,Metropolitano Occidente ...,Hospital Adalberto Steeger (Talagante),6,11,17,5,1263,62.1,0.493,0.357,0.429,0.382,0.469,0.386,0.543,0.362,0.564,0.333
2,Metropolitano Occidente ...,Hospital Dr. Félix Bulnes Cerda,3,6,9,5,1310,65.9,0.580,0.325,0.375,0.409,0.561,0.362,0.328,0.314,0.536,0.436
3,Metropolitano Occidente ...,Hospital San Juan de Dios,29,47,76,30,1066,39.2,0.482,0.554,0.564,0.331,0.438,0.509,0.544,0.410,0.441,0.359
4,Metropolitano Occidente ...,Instituto Traumatológico Dr. Teodoro Gebauer,12,6,18,5,1433,55.5,0.407,0.449,0.468,0.433,0.573,0.392,0.409,0.391,0.418,0.334

In [7]:
df_informacion_historica = pd.read_excel(io=data_path, sheet_name="Información Histórica", header=0, index_col=None)
df_informacion_historica.head()

,Número de llegada,Hospital al que llega,GRD,Día de llegada,Día de salida,Estadia
0,1,Instituto Traumatológico Dr. Teodoro Gebauer,GRD3,1,4,3
1,2,Hospital Clínico San Borja-Arriarán,GRD7,1,5,4
2,3,Hospital Dr. Luis Tisné B.,GRD7,1,5,4
3,4,Hospital Dr. Exequiel González Cortés,GRD10,1,11,10
4,5,Hospital Barros Luco Trudeau,GRD6,1,6,5

In [8]:
df_clase_1 = pd.read_excel(io=data_path, sheet_name="Clase 1", header=0, index_col=None)
df_clase_1.head()

   Dia  Llegada
0    1        4
1    2        5
2    3        5
3    4        2
4    5        4

In [9]:
df_hospitales["Nombre Servicio de Salud"].unique()

array(['Metropolitano Norte                               ',
       'Metropolitano Occidente                           ',
       'Metropolitano Central                             ',
       'Metropolitano Oriente                             ',
       'Metropolitano Sur                                 ',
       'Metropolitano Sur Oriente                         '], dtype=object)

In [23]:
# ¿Cuál de las siguientes alternativas indica correctamente el costo máximo diario de atención en el Servicio de Salud Metropolitano?

df_metropolitano = df_hospitales[df_hospitales['Nombre Servicio de Salud'].str.contains("Metropolitano", case=False)]
df_metropolitano.tail()

,Nombre Servicio de Salud,Nombre Establecimiento,Área Cuidados Intensivos Adultos,Área Cuidados Intermedios Adulto,Total Camas Críticas,Máxima cantidad de camas a aumetar,Costo de instalar una cama [MM$],Costo de operación anual de una cama [MM$],Costo diario GRD1 [MM$],Costo diario GRD2 [MM$],Costo diario GRD3 [MM$],Costo diario GRD4 [MM$],Costo diario GRD5 [MM$],Costo diario GRD6 [MM$],Costo diario GRD7 [MM$],Costo diario GRD8 [MM$],Costo diario GRD9 [MM$],Costo diario GRD10 [MM$]
16,Metropolitano Sur ...,Hospital Parroquial de San Bernardo,6,10,16,4,1051,47.0,0.541,0.546,0.533,0.411,0.534,0.466,0.313,0.500,0.523,0.310
17,Metropolitano Sur Oriente ...,Complejo Hospitalario Dr. Sótero del Río,20,35,55,12,1203,40.6,0.560,0.388,0.584,0.458,0.451,0.595,0.336,0.525,0.472,0.403
18,Metropolitano Sur Oriente ...,Hospital Clínico de la Florida,9,15,24,5,1028,60.0,0.527,0.552,0.431,0.594,0.331,0.341,0.580,0.528,0.537,0.505
19,Metropolitano Sur Oriente ...,Hospital Metropolitano ( ex Militar ),12,20,32,5,1093,46.3,0.549,0.553,0.471,0.346,0.582,0.331,0.456,0.394,0.410,0.563
20,Metropolitano Sur Oriente ...,Hospital Padre Alberto Hurtado (San Ramón),6,10,16,5,1166,43.2,0.479,0.579,0.387,0.509,0.571,0.516,0.584,0.382,0.462,0.424

In [ ]:
grd_columns = [col for col in df_hospitales.columns if "Costo diario GRD" in col]
grd_columns

['Costo diario GRD1 [MM$]',
 'Costo diario GRD2 [MM$]',
 'Costo diario GRD3 [MM$]',
 'Costo diario GRD4 [MM$]',
 'Costo diario GRD5 [MM$]',
 'Costo diario GRD6 [MM$]',
 'Costo diario GRD7 [MM$]',
 'Costo diario GRD8 [MM$]',
 'Costo diario GRD9 [MM$]',
 'Costo diario GRD10 [MM$]']

In [12]:
costo_diario = df_metropolitano[grd_columns].max()
costo_diario

Costo diario GRD1 [MM$]     0.593
Costo diario GRD2 [MM$]     0.599
Costo diario GRD3 [MM$]     0.590
Costo diario GRD4 [MM$]     0.594
Costo diario GRD5 [MM$]     0.597
Costo diario GRD6 [MM$]     0.595
Costo diario GRD7 [MM$]     0.584
Costo diario GRD8 [MM$]     0.572
Costo diario GRD9 [MM$]     0.590
Costo diario GRD10 [MM$]    0.574
dtype: float64

In [13]:
costo_maximo_grd = costo_diario.idxmax()
costo_maximo_value = costo_diario.max()
print(costo_maximo_grd, costo_maximo_value)

Costo diario GRD2 [MM$] 0.599

In [14]:
# Estadia informacion historica

df_informacion_historica.columns

Index(['Número de llegada', 'Hospital al que llega', 'GRD', 'Día de llegada',
       'Día de salida', 'Estadia'],
      dtype='object')

In [15]:
df_informacion_historica[['GRD', 'Estadia']].groupby('GRD').mean().sort_values(by='Estadia', ascending=False)

       Estadia
GRD
GRD1      10.0
GRD10     10.0
GRD4       6.0
GRD6       5.0
GRD9       5.0
GRD2       4.0
GRD5       4.0
GRD7       4.0
GRD8       4.0
GRD3       3.0

In [16]:
# Costo de resolucion ordenado

df_grd.columns

Index(['ID GRD', 'Nombre GRD', 'Costo resolución en Clínica Privada [MM$]'], dtype='object')

In [17]:
df_grd.sort_values(by='Costo resolución en Clínica Privada [MM$]', ascending=False)

  ID GRD      Nombre GRD  Costo resolución en Clínica Privada [MM$]
0   GRD1       Coronario                                      7.917
9  GRD10      Intestinal                                      7.916
4   GRD5     Neurológico                                      6.782
7   GRD8   Oftalmológico                                      6.720
3   GRD4           Renal                                      6.188
8   GRD9    Circulatorio                                      5.524
5   GRD6  Traumatológico                                      4.881
1   GRD2        Hepático                                      3.417
2   GRD3    Respiratorio                                      2.915
6   GRD7       Esofágico                                      2.629

In [18]:
df_hospitales.columns

Index(['Nombre Servicio de Salud', 'Nombre Establecimiento',
       'Área Cuidados Intensivos Adultos', 'Área Cuidados Intermedios Adulto',
       'Total Camas Críticas', 'Máxima cantidad de camas a aumetar',
       'Costo de instalar una cama [MM$]',
       'Costo de operación anual de una cama [MM$]', 'Costo diario GRD1 [MM$]',
       'Costo diario GRD2 [MM$]', 'Costo diario GRD3 [MM$]',
       'Costo diario GRD4 [MM$]', 'Costo diario GRD5 [MM$]',
       'Costo diario GRD6 [MM$]', 'Costo diario GRD7 [MM$]',
       'Costo diario GRD8 [MM$]', 'Costo diario GRD9 [MM$]',
       'Costo diario GRD10 [MM$]'],
      dtype='object')

In [20]:
df_hospitales['Área Cuidados Intensivos Adultos'].mean()

np.float64(14.047619047619047)

In [ ]:
# Utilizando Dataframe y comandos de Python, indique ¿cuál de las siguientes alternativas indica correctamente el máximo de camas críticas que hay en total en los Servicios de Salud Metropolitano Sur y Sur Oriente?
camas_criticas_sur_suroriente = df_hospitales[
    (df_hospitales['Nombre Servicio de Salud'] == 'Metropolitano Sur') |
    (df_hospitales['Nombre Servicio de Salud'] == 'Metropolitano Sur Oriente')]
camas_criticas_sur_suroriente

Empty DataFrame
Columns: [Nombre Servicio de Salud, Nombre Establecimiento, Área Cuidados Intensivos Adultos, Área Cuidados Intermedios Adulto, Total Camas Críticas, Máxima cantidad de camas a aumetar, Costo de instalar una cama [MM$], Costo de operación anual de una cama [MM$], Costo diario GRD1 [MM$], Costo diario GRD2 [MM$], Costo diario GRD3 [MM$], Costo diario GRD4 [MM$], Costo diario GRD5 [MM$], Costo diario GRD6 [MM$], Costo diario GRD7 [MM$], Costo diario GRD8 [MM$], Costo diario GRD9 [MM$], Costo diario GRD10 [MM$]]
Index: []

In [28]:
df_hospitales['Nombre Servicio de Salud'].unique()

array(['Metropolitano Norte                               ',
       'Metropolitano Occidente                           ',
       'Metropolitano Central                             ',
       'Metropolitano Oriente                             ',
       'Metropolitano Sur                                 ',
       'Metropolitano Sur Oriente                         '], dtype=object)

In [32]:
df_hospitales['Nombre Servicio de Salud'] = df_hospitales['Nombre Servicio de Salud'].str.strip()

In [33]:
df_hospitales['Nombre Servicio de Salud'].unique()

array(['Metropolitano Norte', 'Metropolitano Occidente',
       'Metropolitano Central', 'Metropolitano Oriente',
       'Metropolitano Sur', 'Metropolitano Sur Oriente'], dtype=object)

In [34]:
camas_criticas_sur_suroriente = df_hospitales[
    df_hospitales['Nombre Servicio de Salud'].isin(
        ['Metropolitano Sur', 'Metropolitano Sur Oriente'])]
camas_criticas_sur_suroriente

,Nombre Servicio de Salud,Nombre Establecimiento,Área Cuidados Intensivos Adultos,Área Cuidados Intermedios Adulto,Total Camas Críticas,Máxima cantidad de camas a aumetar,Costo de instalar una cama [MM$],Costo de operación anual de una cama [MM$],Costo diario GRD1 [MM$],Costo diario GRD2 [MM$],Costo diario GRD3 [MM$],Costo diario GRD4 [MM$],Costo diario GRD5 [MM$],Costo diario GRD6 [MM$],Costo diario GRD7 [MM$],Costo diario GRD8 [MM$],Costo diario GRD9 [MM$],Costo diario GRD10 [MM$]
12,Metropolitano Sur,Hospital Barros Luco Trudeau,31,43,74,25,1319,42.9,0.551,0.339,0.587,0.416,0.545,0.306,0.347,0.548,0.501,0.419
13,Metropolitano Sur,Hospital de Enfermedades Infecciosas Dr. Lucio...,11,9,20,5,1193,61.6,0.540,0.407,0.590,0.492,0.458,0.361,0.420,0.452,0.331,0.330
14,Metropolitano Sur,Hospital Dr. Exequiel González Cortés,23,8,31,5,1304,51.9,0.398,0.343,0.454,0.493,0.489,0.444,0.323,0.572,0.500,0.310
15,Metropolitano Sur,Hospital El Pino,12,20,32,9,1074,66.1,0.546,0.599,0.550,0.383,0.569,0.442,0.543,0.504,0.590,0.549
16,Metropolitano Sur,Hospital Parroquial de San Bernardo,6,10,16,4,1051,47.0,0.541,0.546,0.533,0.411,0.534,0.466,0.313,0.500,0.523,0.310
17,Metropolitano Sur Oriente,Complejo Hospitalario Dr. Sótero del Río,20,35,55,12,1203,40.6,0.560,0.388,0.584,0.458,0.451,0.595,0.336,0.525,0.472,0.403
18,Metropolitano Sur Oriente,Hospital Clínico de la Florida,9,15,24,5,1028,60.0,0.527,0.552,0.431,0.594,0.331,0.341,0.580,0.528,0.537,0.505
19,Metropolitano Sur Oriente,Hospital Metropolitano ( ex Militar ),12,20,32,5,1093,46.3,0.549,0.553,0.471,0.346,0.582,0.331,0.456,0.394,0.410,0.563
20,Metropolitano Sur Oriente,Hospital Padre Alberto Hurtado (San Ramón),6,10,16,5,1166,43.2,0.479,0.579,0.387,0.509,0.571,0.516,0.584,0.382,0.462,0.424

In [37]:
camas_criticas_sur_suroriente = df_hospitales[
    df_hospitales['Nombre Servicio de Salud'] ==
    'Metropolitano Sur']['Total Camas Críticas'].max()
camas_criticas_sur_suroriente

74

In [38]:
camas_criticas_sur_suroriente = df_hospitales[
    df_hospitales['Nombre Servicio de Salud'] ==
    'Metropolitano Sur Oriente']['Total Camas Críticas'].max()
camas_criticas_sur_suroriente

55

In [43]:
# mas facil hubiera sido

camas_criticas_sur_suroriente = df_hospitales[[
    'Nombre Servicio de Salud', 'Total Camas Críticas'
]].groupby('Nombre Servicio de Salud').max()
camas_criticas_sur_suroriente.sort_values(by='Total Camas Críticas', ascending=False)

                           Total Camas Críticas
Nombre Servicio de Salud
Metropolitano Occidente                      76
Metropolitano Sur                            74
Metropolitano Sur Oriente                    55
Metropolitano Oriente                        46
Metropolitano Central                        44
Metropolitano Norte                          44

In [44]:
# Utilizando el Dataframe Estadía_promedio_Excel.xlsx y comandos de Python, ¿cuál de las siguientes alternativas corresponde a la máxima estadía promedio de entre los GRDs?

df_informacion_historica.head()

,Número de llegada,Hospital al que llega,GRD,Día de llegada,Día de salida,Estadia
0,1,Instituto Traumatológico Dr. Teodoro Gebauer,GRD3,1,4,3
1,2,Hospital Clínico San Borja-Arriarán,GRD7,1,5,4
2,3,Hospital Dr. Luis Tisné B.,GRD7,1,5,4
3,4,Hospital Dr. Exequiel González Cortés,GRD10,1,11,10
4,5,Hospital Barros Luco Trudeau,GRD6,1,6,5

In [45]:
df_informacion_historica.columns

Index(['Número de llegada', 'Hospital al que llega', 'GRD', 'Día de llegada',
       'Día de salida', 'Estadia'],
      dtype='object')

In [47]:
max_estadia_promedio = df_informacion_historica[[
    'GRD', 'Estadia'
]].groupby('GRD').mean().sort_values(by='Estadia', ascending=False)

max_estadia_promedio

       Estadia
GRD
GRD1      10.0
GRD10     10.0
GRD4       6.0
GRD6       5.0
GRD9       5.0
GRD2       4.0
GRD5       4.0
GRD7       4.0
GRD8       4.0
GRD3       3.0

In [48]:
# Utilizando el archivo “Datos.xls”, un Dataframe y comandos en Python, ¿cuál de las siguientes alternativas corresponde al costo total de instalar el máximo de camas críticas posibles en toda la región?

df_hospitales.columns

Index(['Nombre Servicio de Salud', 'Nombre Establecimiento',
       'Área Cuidados Intensivos Adultos', 'Área Cuidados Intermedios Adulto',
       'Total Camas Críticas', 'Máxima cantidad de camas a aumetar',
       'Costo de instalar una cama [MM$]',
       'Costo de operación anual de una cama [MM$]', 'Costo diario GRD1 [MM$]',
       'Costo diario GRD2 [MM$]', 'Costo diario GRD3 [MM$]',
       'Costo diario GRD4 [MM$]', 'Costo diario GRD5 [MM$]',
       'Costo diario GRD6 [MM$]', 'Costo diario GRD7 [MM$]',
       'Costo diario GRD8 [MM$]', 'Costo diario GRD9 [MM$]',
       'Costo diario GRD10 [MM$]'],
      dtype='object')

In [50]:
df_hospitales['costo total de camas a aumentar'] = df_hospitales['Costo de instalar una cama [MM$]'] * df_hospitales['Máxima cantidad de camas a aumetar']
df_hospitales

,Nombre Servicio de Salud,Nombre Establecimiento,Área Cuidados Intensivos Adultos,Área Cuidados Intermedios Adulto,Total Camas Críticas,Máxima cantidad de camas a aumetar,Costo de instalar una cama [MM$],Costo de operación anual de una cama [MM$],Costo diario GRD1 [MM$],Costo diario GRD2 [MM$],Costo diario GRD3 [MM$],Costo diario GRD4 [MM$],Costo diario GRD5 [MM$],Costo diario GRD6 [MM$],Costo diario GRD7 [MM$],Costo diario GRD8 [MM$],Costo diario GRD9 [MM$],Costo diario GRD10 [MM$],costo total de camas a aumentar
0,Metropolitano Norte,Complejo Hospitalario San José,11,33,44,10,1407,47.2,0.593,0.509,0.367,0.492,0.524,0.405,0.571,0.474,0.498,0.305,14070
1,Metropolitano Occidente,Hospital Adalberto Steeger (Talagante),6,11,17,5,1263,62.1,0.493,0.357,0.429,0.382,0.469,0.386,0.543,0.362,0.564,0.333,6315
2,Metropolitano Occidente,Hospital Dr. Félix Bulnes Cerda,3,6,9,5,1310,65.9,0.580,0.325,0.375,0.409,0.561,0.362,0.328,0.314,0.536,0.436,6550
3,Metropolitano Occidente,Hospital San Juan de Dios,29,47,76,30,1066,39.2,0.482,0.554,0.564,0.331,0.438,0.509,0.544,0.410,0.441,0.359,31980
4,Metropolitano Occidente,Instituto Traumatológico Dr. Teodoro Gebauer,12,6,18,5,1433,55.5,0.407,0.449,0.468,0.433,0.573,0.392,0.409,0.391,0.418,0.334,7165
5,Metropolitano Central,Hospital Clínico San Borja-Arriarán,17,26,43,10,1347,63.1,0.509,0.363,0.575,0.534,0.367,0.567,0.576,0.482,0.320,0.574,13470
6,Metropolitano Central,Hospital de Urgencia Asistencia Pública Dr. Al...,24,20,44,10,1256,44.5,0.468,0.509,0.343,0.391,0.390,0.404,0.457,0.411,0.330,0.568,12560
7,Metropolitano Central,Hospital el Carmen,6,12,18,4,1368,49.7,0.444,0.439,0.386,0.569,0.404,0.416,0.302,0.414,0.494,0.425,5472
8,Metropolitano Oriente,Hospital Del Salvador,22,24,46,12,1075,45.4,0.444,0.339,0.345,0.544,0.458,0.531,0.340,0.491,0.377,0.443,12900
9,Metropolitano Oriente,Hospital Dr. Luis Tisné B.,8,16,24,8,1056,56.2,0.386,0.477,0.491,0.312,0.452,0.362,0.435,0.305,0.482,0.421,8448
10,Metropolitano Oriente,Instituto de Neurocirugía Dr. Alfonso Asenjo,12,11,23,8,1256,36.6,0.376,0.481,0.476,0.407,0.573,0.302,0.535,0.520,0.407,0.420,10048
11,Metropolitano Oriente,Instituto Nacional de Enfermedades Respiratori...,15,29,44,15,1422,63.0,0.498,0.465,0.482,0.512,0.597,0.390,0.302,0.566,0.428,0.439,21330
12,Metropolitano Sur,Hospital Barros Luco Trudeau,31,43,74,25,1319,42.9,0.551,0.339,0.587,0.416,0.545,0.306,0.347,0.548,0.501,0.419,32975
13,Metropolitano Sur,Hospital de Enfermedades Infecciosas Dr. Lucio...,11,9,20,5,1193,61.6,0.540,0.407,0.590,0.492,0.458,0.361,0.420,0.452,0.331,0.330,5965
14,Metropolitano Sur,Hospital Dr. Exequiel González Cortés,23,8,31,5,1304,51.9,0.398,0.343,0.454,0.493,0.489,0.444,0.323,0.572,0.500,0.310,6520
15,Metropolitano Sur,Hospital El Pino,12,20,32,9,1074,66.1,0.546,0.599,0.550,0.383,0.569,0.442,0.543,0.504,0.590,0.549,9666
16,Metropolitano Sur,Hospital Parroquial de San Bernardo,6,10,16,4,1051,47.0,0.541,0.546,0.533,0.411,0.534,0.466,0.313,0.500,0.523,0.310,4204
17,Metropolitano Sur Oriente,Complejo Hospitalario Dr. Sótero del Río,20,35,55,12,1203,40.6,0.560,0.388,0.584,0.458,0.451,0.595,0.336,0.525,0.472,0.403,14436
18,Metropolitano Sur Oriente,Hospital Clínico de la Florida,9,15,24,5,1028,60.0,0.527,0.552,0.431,0.594,0.331,0.341,0.580,0.528,0.537,0.505,5140
19,Metropolitano Sur Oriente,Hospital Metropolitano ( ex Militar ),12,20,32,5,1093,46.3,0.549,0.553,0.471,0.346,0.582,0.331,0.456,0.394,0.410,0.563,5465
20,Metropolitano Sur Oriente,Hospital Padre Alberto Hurtado (San Ramón),6,10,16,5,1166,43.2,0.479,0.579,0.387,0.509,0.571,0.516,0.584,0.382,0.462,0.424,5830

In [51]:
df_hospitales['costo total de camas a aumentar'].sum()

np.int64(240509)